# Generated by Django 6.0.1 on 2026-01-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_examattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="exam_type",
            field=models.CharField(
                choices=[("COURSE", "Por Curso"), ("INTEGRAL", "Simulacro Integral")],
                default="COURSE",
                max_length=20,
            ),
        ),
    ]
