# Generated by Django 6.0.1 on 2026-01-10 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_examattempt_exam_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="core.course",
            ),
        ),
    ]
